In [34]:
import pandas as pd
from prettytable import PrettyTable

In [35]:
paris_summer = pd.read_csv("./data/medals_total.csv",encoding="utf-8")
winter_summer_games = pd.read_csv("./data/world_olympedia_olympics_game_medal_tally.csv",encoding="utf-8")

In [36]:
paris_summer

,country_code,country,country_long,Gold Medal,Silver Medal,Bronze Medal,Total
0,USA,United States,United States of America,40,44,42,126
1,CHN,China,People's Republic of China,40,27,24,91
2,JPN,Japan,Japan,20,12,13,45
3,AUS,Australia,Australia,18,19,16,53
4,FRA,France,France,16,26,22,64
...,...,...,...,...,...,...,...
87,PER,Peru,Peru,0,0,1,1
88,QAT,Qatar,Qatar,0,0,1,1
89,SGP,Singapore,Singapore,0,0,1,1
90,SVK,Slovakia,Slovakia,0,0,1,1
91,ZAM,Zambia,Zambia,0,0,1,1

In [37]:
paris_summer_processed = paris_summer.rename(columns={
    "Gold Medal": "gold",
    "Silver Medal": "silver",
    "Bronze Medal": "bronze",
    "Total": "total"
})
paris_summer_processed = paris_summer_processed.groupby("country")[["gold","silver","bronze","total"]].sum()

In [38]:
winter_summer_games

,year,edition,edition_id,country,country_noc,gold,silver,bronze,total
0,1896,1896 Summer Olympics,1,Greece,GRE,10,18,19,47
1,1900,1900 Summer Olympics,2,France,FRA,31,41,40,112
2,1900,1900 Summer Olympics,2,United States,USA,20,13,15,48
3,1904,1904 Summer Olympics,3,United States,USA,80,85,83,248
4,1908,1908 Summer Olympics,5,Great Britain,GBR,56,51,39,146
...,...,...,...,...,...,...,...,...,...
1802,2008,2008 Summer Olympics,53,Australia,AUS,14,15,17,46
1803,2008,2008 Summer Olympics,53,Cuba,CUB,3,10,17,30
1804,2012,2012 Summer Olympics,54,Japan,JPN,7,14,17,38
1805,2016,2016 Summer Olympics,59,Great Britain,GBR,27,23,17,67
1806,2020,2020 Summer Olympics,61,Japan,JPN,27,14,17,58

In [39]:
# Separar por jogos de verão/inverno
summer = winter_summer_games[winter_summer_games["edition"].str.contains("Summer")]
winter = winter_summer_games[winter_summer_games["edition"].str.contains("Winter")]

summer_medals = summer.groupby("country")["total"].sum()
winter_medals = winter.groupby("country")["total"].sum()

In [40]:
summer_medals = summer_medals.sort_values(ascending=False)
winter_medals = winter_medals.sort_values(ascending=False)

In [41]:
summer_medals = pd.concat([summer_medals, paris_summer_processed])

In [42]:
print("Summer medals:")
print(summer_medals)

print("\nWinter medals:")
print(winter_medals)

Summer medals:
               total  gold  silver  bronze
country
United States   2655   NaN     NaN     NaN
Soviet Union    1010   NaN     NaN     NaN
Great Britain    927   NaN     NaN     NaN
Germany          791   NaN     NaN     NaN
France           773   NaN     NaN     NaN
...              ...   ...     ...     ...
Uganda             2   1.0     1.0     0.0
Ukraine           12   3.0     5.0     4.0
United States    126  40.0    44.0    42.0
Uzbekistan        13   8.0     2.0     3.0
Zambia             1   0.0     0.0     1.0

[245 rows x 4 columns]

Winter medals:
country
Norway                                   405
United States                            330
Germany                                  286
Austria                                  250
Canada                                   225
Soviet Union                             194
Sweden                                   176
Finland                                  175
Switzerland                              168
Netherlands                              147
Italy                                    141
France                                   138
Russian Federation                       120
East Germany                             110
Republic of Korea                         79
People's Republic of China                77
Japan                                     76
ROC                                       49
West Germany                              39
Czechia                                   34
Great Britain                             34
Czechoslovakia                            25
Slovenia                                  24
Unified Team                              23
Poland                                    23
Belarus                                   20
Australia                                 19
Croatia                                   11
Latvia                                    10
Slovakia                                  10
Liechtenstein                             10
Hungary                                   10
Ukraine                                    9
Kazakhstan                                 8
Belgium                                    8
Estonia                                    8
Bulgaria                                   6
New Zealand                                6
Spain                                      5
Yugoslavia                                 4
Luxembourg                                 2
Democratic People's Republic of Korea      2
Denmark                                    1
Mixed team                                 1
Romania                                    1
Uzbekistan                                 1
Name: total, dtype: int64

In [43]:
summer_medals = (
    summer.groupby("country")[["gold","silver","bronze","total"]]
    .sum()
    .sort_values("total", ascending=False)
)

winter_medals = (
    winter.groupby("country")[["gold","silver","bronze","total"]]
    .sum()
    .sort_values("total", ascending=False)
)

total_medals = (
    winter_summer_games.groupby("country")[["gold","silver","bronze","total"]]
    .sum()
    .sort_values("total", ascending=False)
)

In [44]:
def dataframe_to_prettytable(df, title):
    table = PrettyTable()
    table.title = title
    table.field_names = ["Country", "Gold", "Silver", "Bronze", "Total"]

    for country, row in df.iterrows():
        table.add_row([country, row["gold"], row["silver"], row["bronze"], row["total"]])

    print(table)

In [45]:
dataframe_to_prettytable(summer_medals, "Medalhas – Jogos de Verão")

+------------------------------------------------------------------------+
|                       Medalhas – Jogos de Verão                        |
+---------------------------------------+------+--------+--------+-------+
|                Country                | Gold | Silver | Bronze | Total |
+---------------------------------------+------+--------+--------+-------+
|             United States             | 1070 |  841   |  744   |  2655 |
|              Soviet Union             | 395  |  319   |  296   |  1010 |
|             Great Britain             | 291  |  323   |  313   |  927  |
|                Germany                | 237  |  264   |  290   |  791  |
|                 France                | 231  |  257   |  285   |  773  |
|       People's Republic of China      | 263  |  199   |  174   |  636  |
|                 Italy                 | 222  |  193   |  214   |  629  |
|               Australia               | 162  |  170   |  209   |  541  |
|                Hungary                | 182  |  156   |  177   |  515  |
|                 Sweden                | 146  |  177   |  181   |  504  |
|                 Japan                 | 169  |  150   |  180   |  499  |
|           Russian Federation          | 148  |  130   |  153   |  431  |
|              East Germany             | 153  |  129   |  127   |  409  |
|              Netherlands              |  98  |  106   |  125   |  329  |
|                 Canada                |  70  |  111   |  144   |  325  |
|                Finland                | 104  |   86   |  120   |  310  |
|                Romania                |  90  |   97   |  121   |  308  |
|                 Poland                |  75  |   91   |  140   |  306  |
|           Republic of Korea           |  96  |   91   |  100   |  287  |
|                  Cuba                 |  84  |   69   |   82   |  235  |
|                Bulgaria               |  54  |   88   |   82   |  224  |
|                Denmark                |  48  |   82   |   83   |  213  |
|              Switzerland              |  56  |   84   |   72   |  212  |
|              West Germany             |  56  |   67   |   81   |  204  |
|                 Spain                 |  48  |   72   |   49   |  169  |
|                Belgium                |  46  |   56   |   64   |  166  |
|                 Norway                |  59  |   53   |   50   |  162  |
|                 Brazil                |  37  |   42   |   71   |  150  |
|             Czechoslovakia            |  49  |   50   |   47   |  146  |
|                Ukraine                |  35  |   36   |   68   |  139  |
|              New Zealand              |  53  |   33   |   51   |  137  |
|                 Greece                |  36  |   45   |   41   |  122  |
|                 Kenya                 |  35  |   42   |   36   |  113  |
|              Unified Team             |  45  |   38   |   29   |  112  |
|                Türkiye                |  41  |   26   |   36   |  103  |
|                Austria                |  22  |   37   |   43   |  102  |
|              South Africa             |  27  |   34   |   30   |   91  |
|                Jamaica                |  26  |   36   |   26   |   88  |
|                Belarus                |  13  |   30   |   42   |   85  |
|               Yugoslavia              |  26  |   29   |   28   |   83  |
|               Argentina               |  21  |   26   |   30   |   77  |
|        Islamic Republic of Iran       |  24  |   23   |   29   |   76  |
|                 Mexico                |  13  |   24   |   35   |   72  |
|                  ROC                  |  20  |   28   |   23   |   71  |
|               Kazakhstan              |  14  |   21   |   36   |   71  |
|                Czechia                |  19  |   22   |   26   |   67  |
|                Ethiopia               |  23  |   12   |   23   |   58  |
| Democratic People's Republic of Korea |  16  |   16   |   23   |   55  |
|               Azerbaijan              |  7   |   14   |   28   |   49  |
|                Croatia                |  14  |   13   |   14   |   41  |
|                Georgia                |  10  |   12   |   18   |   40  |
|                Ireland                |  11  |   11   |   16   |   38  |
|               Indonesia               |  8   |   14   |   15   |   37  |
|               Uzbekistan              |  10  |   6    |   20   |   36  |
|                 Egypt                 |  8   |   10   |   18   |   36  |
|                Estonia                |  10  |   9    |   17   |   36  |
|             Chinese Taipei            |  7   |   11   |   18   |   36  |
|                 India                 |  10  |   9    |   16   |   35  |
|                Thailand               |  10  |   8    |   17   |   35  |
|                Colombia               |  5   |   13   |   16   |   34  |
|                Slovakia               |  10  |   14   |   8    |   32  |
|                Mongolia               |  2   |   11   |   17   |   30  |
|                Portugal               |  5   |   9    |   14   |   28  |
|                Slovenia               |  8   |   9    |   11   |   28  |
|                Nigeria                |  3   |   11   |   13   |   27  |
|               Lithuania               |  6   |   7    |   13   |   26  |
|                 Serbia                |  6   |   7    |   11   |   24  |
|                Morocco                |  7   |   5    |   12   |   24  |
|                 Latvia                |  4   |   11   |   6    |   21  |
|          Trinidad and Tobago          |  3   |   5    |   11   |   19  |
|               Venezuela               |  3   |   7    |   9    |   19  |
|                Armenia                |  2   |   8    |   8    |   18  |
|                Algeria                |  5   |   4    |   8    |   17  |
|              The Bahamas              |  8   |   2    |   6    |   16  |
|                Tunisia                |  5   |   3    |   7    |   15  |
|              Philippines              |  1   |   5    |   8    |   14  |
|                 Chile                 |  2   |   7    |   4    |   13  |
|                 Israel                |  3   |   1    |   9    |   13  |
|                Malaysia               |  0   |   8    |   5    |   13  |
|              Australasia              |  3   |   4    |   5    |   12  |
|           Dominican Republic          |  3   |   5    |   4    |   12  |
|                 Uganda                |  4   |   4    |   3    |   11  |
|              Puerto Rico              |  2   |   2    |   6    |   10  |
|                Uruguay                |  2   |   2    |   6    |   10  |
|                Pakistan               |  3   |   3    |   4    |   10  |
|            Hong Kong, China           |  2   |   3    |   4    |   9   |
|         Serbia and Montenegro         |  2   |   4    |   3    |   9   |
|               Mixed team              |  3   |   2    |   4    |   9   |
|                Zimbabwe               |  3   |   4    |   1    |   8   |
|                 Qatar                 |  2   |   2    |   4    |   8   |
|               Kyrgyzstan              |  0   |   3    |   4    |   7   |
|          Republic of Moldova          |  0   |   2    |   4    |   6   |
|                Cameroon               |  3   |   1    |   2    |   6   |
|                Namibia                |  0   |   5    |   0    |   5   |
|               Luxembourg              |  3   |   2    |   0    |   5   |
|               Singapore               |  1   |   2    |   2    |   5   |
|                Vietnam                |  1   |   3    |   1    |   5   |
|      Independent Olympic Athletes     |  1   |   1    |   3    |   5   |
|                Ecuador                |  3   |   2    |   0    |   5   |
|                 Ghana                 |  0   |   1    |   4    |   5   |
|                Bahrain                |  2   |   2    |   0    |   4   |
|                Iceland                |  0   |   2    |   2    |   4   |
|                Lebanon                |  0   |   2    |   2    |   4   |
|               Costa Rica              |  1   |   1    |   2    |   4   |
|                Bohemia                |  0   |   1    |   3    |   4   |
|               Tajikistan              |  1   |   1    |   2    |   4   |
|                  Peru                 |  1   |   3    |   0    |   4   |
|          Syrian Arab Republic         |  1   |   1    |   2    |   4   |
|        Kingdom of Saudi Arabia        |  0   |   2    |   2    |   4   |
|             Côte d'Ivoire             |  1   |   1    |   2    |   4   |
|                 Kosovo                |  3   |   0    |   0    |   3   |
|                  Fiji                 |  2   |   0    |   1    |   3   |
|                Grenada                |  1   |   1    |   1    |   3   |
|               San Marino              |  0   |   1    |   2    |   3   |
|                 Panama                |  1   |   0    |   2    |   3   |
|                 Kuwait                |  0   |   0    |   3    |   3   |
|                 Jordan                |  1   |   1    |   1    |   3   |
|                Bermuda                |  1   |   0    |   1    |   2   |
|              Afghanistan              |  0   |   0    |   2    |   2   |
|                Botswana               |  0   |   1    |   1    |   2   |
|                Burundi                |  1   |   1    |   0    |   2   |
|                Suriname               |  1   |   0    |   1    |   2   |
|               Sri Lanka               |  0   |   2    |   0    |   2   |
|                 Zambia                |  0   |   1    |   1    |   2   |
|          United Arab Republic         |  0   |   1    |   1    |   2   |
|         West Indies Federation        |  0   |   0    |   2    |   2   |
|      United Republic of Tanzania      |  0   |   2    |   0    |   2   |
|          United Arab Emirates         |  1   |   0    |   1    |   2   |
|            North Macedonia            |  0   |   1    |   1    |   2   |
|                 Niger                 |  0   |   1    |   1    |   2   |
|                 Haiti                 |  0   |   1    |   1    |   2   |
|               Mozambique              |  1   |   0    |   1    |   2   |
|                Barbados               |  0   |   0    |   1    |   1   |
|              Burkina Faso             |  0   |   0    |   1    |   1   |
|                Djibouti               |  0   |   0    |   1    |   1   |
|                 Cyprus                |  0   |   1    |   0    |   1   |
|               Guatemala               |  0   |   1    |   0    |   1   |
|                 Monaco                |  0   |   0    |   1    |   1   |
|               Montenegro              |  0   |   1    |   0    |   1   |
|               Mauritius               |  0   |   0    |   1    |   1   |
|                  Iraq                 |  0   |   0    |   1    |   1   |
|                Eritrea                |  0   |   0    |   1    |   1   |
|                 Gabon                 |  0   |   1    |   0    |   1   |
|                 Guyana                |  0   |   0    |   1    |   1   |
|                Paraguay               |  0   |   1    |   0    |   1   |
|                 Samoa                 |  0   |   1    |   0    |   1   |
|                Senegal                |  0   |   1    |   0    |   1   |
|          Netherlands Antilles         |  0   |   1    |   0    |   1   |
|                 Sudan                 |  0   |   1    |   0    |   1   |
|              Turkmenistan             |  0   |   1    |   0    |   1   |
|                 Tonga                 |  0   |   1    |   0    |   1   |
|                  Togo                 |  0   |   0    |   1    |   1   |
|      United States Virgin Islands     |  0   |   1    |   0    |   1   |
+---------------------------------------+------+--------+--------+-------+

In [46]:
dataframe_to_prettytable(winter_medals, "Medalhas – Jogos de Inverno")

+------------------------------------------------------------------------+
|                      Medalhas – Jogos de Inverno                       |
+---------------------------------------+------+--------+--------+-------+
|                Country                | Gold | Silver | Bronze | Total |
+---------------------------------------+------+--------+--------+-------+
|                 Norway                | 148  |  134   |  123   |  405  |
|             United States             | 113  |  122   |   95   |  330  |
|                Germany                | 112  |  104   |   70   |  286  |
|                Austria                |  71  |   88   |   91   |  250  |
|                 Canada                |  77  |   72   |   76   |  225  |
|              Soviet Union             |  78  |   57   |   59   |  194  |
|                 Sweden                |  65  |   51   |   60   |  176  |
|                Finland                |  45  |   65   |   65   |  175  |
|              Switzerland              |  63  |   47   |   58   |  168  |
|              Netherlands              |  53  |   49   |   45   |  147  |
|                 Italy                 |  42  |   43   |   56   |  141  |
|                 France                |  41  |   42   |   55   |  138  |
|           Russian Federation          |  46  |   39   |   35   |  120  |
|              East Germany             |  39  |   36   |   35   |  110  |
|           Republic of Korea           |  33  |   30   |   16   |   79  |
|       People's Republic of China      |  22  |   32   |   23   |   77  |
|                 Japan                 |  17  |   28   |   31   |   76  |
|                  ROC                  |  8   |   18   |   23   |   49  |
|              West Germany             |  11  |   15   |   13   |   39  |
|                Czechia                |  10  |   11   |   13   |   34  |
|             Great Britain             |  12  |   5    |   17   |   34  |
|             Czechoslovakia            |  2   |   8    |   15   |   25  |
|                Slovenia               |  4   |   8    |   12   |   24  |
|              Unified Team             |  9   |   6    |   8    |   23  |
|                 Poland                |  7   |   7    |   9    |   23  |
|                Belarus                |  8   |   7    |   5    |   20  |
|               Australia               |  6   |   7    |   6    |   19  |
|                Croatia                |  4   |   6    |   1    |   11  |
|                 Latvia                |  1   |   3    |   6    |   10  |
|                Slovakia               |  4   |   4    |   2    |   10  |
|             Liechtenstein             |  2   |   2    |   6    |   10  |
|                Hungary                |  2   |   2    |   6    |   10  |
|                Ukraine                |  3   |   2    |   4    |   9   |
|               Kazakhstan              |  1   |   3    |   4    |   8   |
|                Belgium                |  2   |   2    |   4    |   8   |
|                Estonia                |  4   |   2    |   2    |   8   |
|                Bulgaria               |  1   |   2    |   3    |   6   |
|              New Zealand              |  2   |   2    |   2    |   6   |
|                 Spain                 |  1   |   1    |   3    |   5   |
|               Yugoslavia              |  0   |   3    |   1    |   4   |
|               Luxembourg              |  0   |   2    |   0    |   2   |
| Democratic People's Republic of Korea |  0   |   1    |   1    |   2   |
|                Denmark                |  0   |   1    |   0    |   1   |
|               Mixed team              |  1   |   0    |   0    |   1   |
|                Romania                |  0   |   0    |   1    |   1   |
|               Uzbekistan              |  1   |   0    |   0    |   1   |
+---------------------------------------+------+--------+--------+-------+

In [47]:
dataframe_to_prettytable(total_medals, "Medalhas – Total Geral")

+------------------------------------------------------------------------+
|                         Medalhas – Total Geral                         |
+---------------------------------------+------+--------+--------+-------+
|                Country                | Gold | Silver | Bronze | Total |
+---------------------------------------+------+--------+--------+-------+
|             United States             | 1195 |  969   |  845   |  3009 |
|              Soviet Union             | 473  |  376   |  355   |  1204 |
|                Germany                | 355  |  377   |  366   |  1098 |
|             Great Britain             | 312  |  339   |  337   |  988  |
|                 France                | 287  |  308   |  356   |  951  |
|                 Italy                 | 271  |  244   |  274   |  789  |
|       People's Republic of China      | 285  |  231   |  197   |  713  |
|                 Sweden                | 216  |  233   |  248   |  697  |
|                 Japan                 | 186  |  178   |  211   |  575  |
|                 Norway                | 208  |  188   |  173   |  569  |
|               Australia               | 168  |  177   |  218   |  563  |
|                 Canada                | 148  |  184   |  221   |  553  |
|           Russian Federation          | 194  |  169   |  188   |  551  |
|                Hungary                | 186  |  163   |  186   |  535  |
|              East Germany             | 192  |  165   |  162   |  519  |
|                Finland                | 151  |  152   |  186   |  489  |
|              Netherlands              | 151  |  156   |  172   |  479  |
|              Switzerland              | 123  |  134   |  132   |  389  |
|           Republic of Korea           | 129  |  121   |  116   |  366  |
|                Austria                |  96  |  128   |  137   |  361  |
|                 Poland                |  82  |   98   |  149   |  329  |
|                Romania                |  90  |   97   |  122   |  309  |
|              West Germany             |  67  |   82   |   94   |  243  |
|                  Cuba                 |  84  |   69   |   82   |  235  |
|                Bulgaria               |  55  |   90   |   85   |  230  |
|                Denmark                |  51  |   86   |   84   |  221  |
|                Belgium                |  50  |   60   |   71   |  181  |
|                 Spain                 |  49  |   73   |   52   |  174  |
|             Czechoslovakia            |  51  |   58   |   62   |  171  |
|                 Greece                |  44  |   59   |   54   |  157  |
|                 Brazil                |  37  |   42   |   71   |  150  |
|                Ukraine                |  38  |   38   |   72   |  148  |
|              New Zealand              |  55  |   35   |   53   |  143  |
|              Unified Team             |  54  |   44   |   37   |  135  |
|                  ROC                  |  28  |   46   |   46   |  120  |
|                 Kenya                 |  35  |   42   |   36   |  113  |
|                Belarus                |  21  |   37   |   47   |  105  |
|                Türkiye                |  41  |   26   |   36   |  103  |
|                Czechia                |  29  |   33   |   39   |  101  |
|              South Africa             |  27  |   34   |   30   |   91  |
|                Jamaica                |  26  |   36   |   26   |   88  |
|               Yugoslavia              |  26  |   32   |   29   |   87  |
|               Kazakhstan              |  15  |   24   |   40   |   79  |
|               Argentina               |  21  |   26   |   30   |   77  |
|        Islamic Republic of Iran       |  24  |   23   |   29   |   76  |
|                 Mexico                |  13  |   24   |   35   |   72  |
|                Ethiopia               |  23  |   12   |   23   |   58  |
| Democratic People's Republic of Korea |  16  |   17   |   24   |   57  |
|                Slovenia               |  12  |   17   |   23   |   52  |
|                Croatia                |  18  |   19   |   15   |   52  |
|               Azerbaijan              |  7   |   14   |   28   |   49  |
|                Estonia                |  14  |   11   |   19   |   44  |
|                Slovakia               |  14  |   18   |   10   |   42  |
|                Georgia                |  10  |   12   |   18   |   40  |
|                Ireland                |  11  |   11   |   16   |   38  |
|               Indonesia               |  8   |   14   |   15   |   37  |
|               Uzbekistan              |  11  |   6    |   20   |   37  |
|             Chinese Taipei            |  7   |   11   |   18   |   36  |
|                 Egypt                 |  8   |   10   |   18   |   36  |
|                 India                 |  10  |   9    |   16   |   35  |
|                Thailand               |  10  |   8    |   17   |   35  |
|                Colombia               |  5   |   13   |   16   |   34  |
|                 Latvia                |  5   |   14   |   12   |   31  |
|                Mongolia               |  2   |   11   |   17   |   30  |
|                Portugal               |  5   |   9    |   14   |   28  |
|                Nigeria                |  3   |   11   |   13   |   27  |
|               Lithuania               |  6   |   7    |   13   |   26  |
|                 Serbia                |  6   |   7    |   11   |   24  |
|                Morocco                |  7   |   5    |   12   |   24  |
|               Venezuela               |  3   |   7    |   9    |   19  |
|          Trinidad and Tobago          |  3   |   5    |   11   |   19  |
|                Armenia                |  2   |   8    |   8    |   18  |
|                Algeria                |  5   |   4    |   8    |   17  |
|              The Bahamas              |  8   |   2    |   6    |   16  |
|                Tunisia                |  5   |   3    |   7    |   15  |
|              Philippines              |  1   |   5    |   8    |   14  |
|                Malaysia               |  0   |   8    |   5    |   13  |
|                 Chile                 |  2   |   7    |   4    |   13  |
|                 Israel                |  3   |   1    |   9    |   13  |
|           Dominican Republic          |  3   |   5    |   4    |   12  |
|              Australasia              |  3   |   4    |   5    |   12  |
|                 Uganda                |  4   |   4    |   3    |   11  |
|             Liechtenstein             |  2   |   2    |   6    |   10  |
|               Mixed team              |  4   |   2    |   4    |   10  |
|                Pakistan               |  3   |   3    |   4    |   10  |
|              Puerto Rico              |  2   |   2    |   6    |   10  |
|                Uruguay                |  2   |   2    |   6    |   10  |
|         Serbia and Montenegro         |  2   |   4    |   3    |   9   |
|            Hong Kong, China           |  2   |   3    |   4    |   9   |
|                Zimbabwe               |  3   |   4    |   1    |   8   |
|                 Qatar                 |  2   |   2    |   4    |   8   |
|               Luxembourg              |  3   |   4    |   0    |   7   |
|               Kyrgyzstan              |  0   |   3    |   4    |   7   |
|                Bohemia                |  0   |   1    |   5    |   6   |
|                Cameroon               |  3   |   1    |   2    |   6   |
|          Republic of Moldova          |  0   |   2    |   4    |   6   |
|               Singapore               |  1   |   2    |   2    |   5   |
|                Vietnam                |  1   |   3    |   1    |   5   |
|                Namibia                |  0   |   5    |   0    |   5   |
|                Ecuador                |  3   |   2    |   0    |   5   |
|      Independent Olympic Athletes     |  1   |   1    |   3    |   5   |
|                 Ghana                 |  0   |   1    |   4    |   5   |
|             Côte d'Ivoire             |  1   |   1    |   2    |   4   |
|                Lebanon                |  0   |   2    |   2    |   4   |
|               Costa Rica              |  1   |   1    |   2    |   4   |
|                Bahrain                |  2   |   2    |   0    |   4   |
|               Tajikistan              |  1   |   1    |   2    |   4   |
|                  Peru                 |  1   |   3    |   0    |   4   |
|          Syrian Arab Republic         |  1   |   1    |   2    |   4   |
|        Kingdom of Saudi Arabia        |  0   |   2    |   2    |   4   |
|                Iceland                |  0   |   2    |   2    |   4   |
|                 Kosovo                |  3   |   0    |   0    |   3   |
|                Grenada                |  1   |   1    |   1    |   3   |
|                  Fiji                 |  2   |   0    |   1    |   3   |
|               San Marino              |  0   |   1    |   2    |   3   |
|                 Panama                |  1   |   0    |   2    |   3   |
|                 Kuwait                |  0   |   0    |   3    |   3   |
|                 Jordan                |  1   |   1    |   1    |   3   |
|              Afghanistan              |  0   |   0    |   2    |   2   |
|                Bermuda                |  1   |   0    |   1    |   2   |
|                Botswana               |  0   |   1    |   1    |   2   |
|                Burundi                |  1   |   1    |   0    |   2   |
|                Suriname               |  1   |   0    |   1    |   2   |
|               Sri Lanka               |  0   |   2    |   0    |   2   |
|                 Zambia                |  0   |   1    |   1    |   2   |
|          United Arab Republic         |  0   |   1    |   1    |   2   |
|         West Indies Federation        |  0   |   0    |   2    |   2   |
|      United Republic of Tanzania      |  0   |   2    |   0    |   2   |
|          United Arab Emirates         |  1   |   0    |   1    |   2   |
|            North Macedonia            |  0   |   1    |   1    |   2   |
|                 Niger                 |  0   |   1    |   1    |   2   |
|                 Haiti                 |  0   |   1    |   1    |   2   |
|               Mozambique              |  1   |   0    |   1    |   2   |
|                Barbados               |  0   |   0    |   1    |   1   |
|              Burkina Faso             |  0   |   0    |   1    |   1   |
|                Djibouti               |  0   |   0    |   1    |   1   |
|                 Cyprus                |  0   |   1    |   0    |   1   |
|               Guatemala               |  0   |   1    |   0    |   1   |
|                 Monaco                |  0   |   0    |   1    |   1   |
|               Montenegro              |  0   |   1    |   0    |   1   |
|               Mauritius               |  0   |   0    |   1    |   1   |
|                  Iraq                 |  0   |   0    |   1    |   1   |
|                Eritrea                |  0   |   0    |   1    |   1   |
|                 Gabon                 |  0   |   1    |   0    |   1   |
|                 Guyana                |  0   |   0    |   1    |   1   |
|                Paraguay               |  0   |   1    |   0    |   1   |
|                 Samoa                 |  0   |   1    |   0    |   1   |
|                Senegal                |  0   |   1    |   0    |   1   |
|          Netherlands Antilles         |  0   |   1    |   0    |   1   |
|                 Sudan                 |  0   |   1    |   0    |   1   |
|              Turkmenistan             |  0   |   1    |   0    |   1   |
|                 Tonga                 |  0   |   1    |   0    |   1   |
|                  Togo                 |  0   |   0    |   1    |   1   |
|      United States Virgin Islands     |  0   |   1    |   0    |   1   |
+---------------------------------------+------+--------+--------+-------+